version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      NODE_ENV: development
      MONGO_URL: "mongodb://mongoadmin:secret@mongodb:27017/mydb?authSource=admin"
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: