# Dockerfile for backend
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies by copying
# package.json and package-lock.json
COPY backend/package*.json ./

# Install dependencies
RUN npm install 

# Bundle app source
COPY backend/ .

# Expose the port the app runs on
EXPOSE 3002

# Command to run the app
CMD [ "node", "server.js" ]
